apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: sample-go-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: sample-go-app
  type: ClusterIP
